DROP TABLE IF EXISTS public.blog_posts CASCADE;

-- 1. Create the blog_posts table
CREATE TABLE public.blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    title TEXT NOT NULL,
    excerpt TEXT,
    content TEXT,
    date DATE NOT NULL,
    author VARCHAR(255),
    category VARCHAR(100),
    image_url TEXT
  );

-- 2. Enable RLS
ALTER TABLE
  public.blog_posts ENABLE ROW LEVEL SECURITY;

-- 3. Create Policy for public read access
CREATE POLICY "Public can read blog posts" ON public.blog_posts FOR
SELECT
  USING (true);

-- 4. Insert Sample Data
INSERT INTO
  public.blog_posts (
    title,
    excerpt,
    content,
    date,
    author,
    category,
    image_url
  )
VALUES
  (
    'The Future of AI in Malaysian Bookkeeping',
    'Discover how artificial intelligence is set to revolutionize financial management for SMEs in Malaysia, from automated data entry to predictive insights.',
    'Full blog post content about AI in bookkeeping...',
    '2024-07-28',
    'Ibn Zelt Staff',
    'Technology',
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop'
  ),
  (
    '5 Common Tax Mistakes Malaysian SMEs Make',
    'Navigating the Malaysian tax landscape can be tricky. Here are five common pitfalls for small and medium-sized enterprises and how to avoid them.',
    'Full blog post content about common tax mistakes...',
    '2024-07-20',
    'Ashraf Yusof',
    'Tax & Compliance',
    'https://images.unsplash.com/photo-1554224155-8d04421cd6c3?q=80&w=2070&auto=format&fit=crop'
  ),
  (
    'Why Cloud ERP is a Game-Changer for Your Business',
    'Move beyond spreadsheets. A cloud-based ERP system can integrate all your core business processes for improved efficiency and real-time decision-making.',
    'Full blog post content about Cloud ERP...',
    '2024-07-15',
    'Ibn Zelt Staff',
    'Business Growth',
    'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?q=80&w=2070&auto=format&fit=crop'
  ); 