-- Enable RLS
ALTER TABLE
  public.individual_tax_rates ENABLE ROW LEVEL SECURITY;

ALTER TABLE
  public.corporate_tax_rates ENABLE ROW LEVEL SECURITY;

ALTER TABLE
  public.tax_reliefs ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Public can read individual tax rates" ON public.individual_tax_rates FOR
SELECT
  USING (true);

CREATE POLICY "Public can read corporate tax rates" ON public.corporate_tax_rates FOR
SELECT
  USING (true);

CREATE POLICY "Public can read tax reliefs" ON public.tax_reliefs FOR
SELECT
  USING (true);

-- Create tax tables
CREATE TABLE
  IF NOT EXISTS public.individual_tax_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year SMALLINT NOT NULL,
    category VARCHAR(10) NOT NULL,
    "chargeable_income_min" INT NOT NULL,
    "chargeable_income_max" INT,
    "bracket_type" VARCHAR(50) NOT NULL,
    calculation_desc VARCHAR(255) NOT NULL,
    rate SMALLINT NOT NULL,
    tax_on_bracket INT
  );

CREATE TABLE
  IF NOT EXISTS public.corporate_tax_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year SMALLINT NOT NULL,
    category VARCHAR(255) NOT NULL,
    "chargeable_income_min" BIGINT,
    "chargeable_income_max" BIGINT,
    rate NUMERIC(5, 2) NOT NULL,
    notes TEXT
  );

CREATE TABLE
  IF NOT EXISTS public.tax_reliefs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year SMALLINT NOT NULL,
    category VARCHAR(255) NOT NULL,
    item VARCHAR(255) NOT NULL,
    relief_amount INT,
    notes TEXT
  );

-- Clear existing data
TRUNCATE TABLE individual_tax_rates RESTART IDENTITY CASCADE;

TRUNCATE TABLE corporate_tax_rates RESTART IDENTITY CASCADE;

TRUNCATE TABLE tax_reliefs RESTART IDENTITY CASCADE;

-- Insert data for 2025 (YA 2025)
INSERT INTO
  individual_tax_rates (
    year,
    category,
    chargeable_income_min,
    chargeable_income_max,
    bracket_type,
    calculation_desc,
    rate,
    tax_on_bracket
  )
VALUES
  (
    2025,
    'A',
    0,
    5000,
    'First',
    '5,000',
    0,
    0
  ),
  (
    2025,
    'B',
    5001,
    10000,
    'Next',
    '5,000',
    1,
    50
  ),
  (
    2025,
    'C',
    10001,
    20000,
    'Next',
    '10,000',
    1,
    100
  ),
  (
    2025,
    'D',
    20001,
    35000,
    'Next',
    '15,000',
    3,
    450
  ),
  (
    2025,
    'E',
    35001,
    50000,
    'Next',
    '15,000',
    6,
    900
  ),
  (
    2025,
    'F',
    50001,
    70000,
    'Next',
    '20,000',
    11,
    2200
  ),
  (
    2025,
    'G',
    70001,
    100000,
    'Next',
    '30,000',
    19,
    5700
  ),
  (
    2025,
    'H',
    100001,
    400000,
    'Next',
    '299,999',
    25,
    74999
  ),
  (
    2025,
    'I',
    400001,
    600000,
    'Next',
    '199,999',
    26,
    51999
  ),
  (
    2025,
    'J',
    600001,
    1000000,
    'Next',
    '399,999',
    28,
    111999
  ),
  (
    2025,
    'K',
    1000001,
    NULL,
    'Excess',
    'Every next RM',
    30,
    NULL
  );

INSERT INTO
  corporate_tax_rates (
    year,
    category,
    chargeable_income_min,
    chargeable_income_max,
    rate,
    notes
  )
VALUES
  (
    2025,
    'SME',
    0,
    600000,
    17.00,
    'For SMEs with paid-up capital of RM2.5 million or less, and gross business income of RM50 million or less.'
  ),
  (
    2025,
    'SME (Excess)',
    600001,
    NULL,
    24.00,
    'For SMEs, on income exceeding RM600,000.'
  ),
  (
    2025,
    'Non-SME',
    NULL,
    NULL,
    24.00,
    'For companies with paid-up capital of more than RM2.5 million.'
  );

INSERT INTO
  tax_reliefs (
    year,
    category,
    item,
    relief_amount,
    notes
  )
VALUES
  (
    2025,
    'Individual',
    'Individual and dependent relatives',
    9000,
    'Automatic'
  ),
  (
    2025,
    'Medical',
    'Medical treatment for parents',
    8000,
    'Limited'
  ),
  (
    2025,
    'Lifestyle',
    'Purchase of books, journals, magazines, etc.',
    2500,
    'Limited'
  ),
  (
    2025,
    'Education',
    'Self-education fees (up to tertiary)',
    7000,
    'Limited'
  ),
  (
    2025,
    'Spouse',
    'Disabled spouse',
    5000,
    'Additional'
  );

-- Insert data for 2024 (YA 2024)
INSERT INTO
  individual_tax_rates (
    year,
    category,
    chargeable_income_min,
    chargeable_income_max,
    bracket_type,
    calculation_desc,
    rate,
    tax_on_bracket
  )
VALUES
  (
    2024,
    'A',
    0,
    5000,
    'First',
    '5,000',
    0,
    0
  ),
  (
    2024,
    'B',
    5001,
    20000,
    'Next',
    '15,000',
    1,
    150
  ),
  (
    2024,
    'C',
    20001,
    35000,
    'Next',
    '15,000',
    3,
    450
  ),
  (
    2024,
    'D',
    35001,
    50000,
    'Next',
    '15,000',
    8,
    1200
  ),
  (
    2024,
    'E',
    50001,
    70000,
    'Next',
    '20,000',
    14,
    2800
  ),
  (
    2024,
    'F',
    70001,
    100000,
    'Next',
    '30,000',
    21,
    6300
  ),
  (
    2024,
    'G',
    100001,
    250000,
    'Next',
    '150,000',
    24,
    36000
  ),
  (
    2024,
    'H',
    250001,
    400000,
    'Next',
    '150,000',
    24,
    36000
  ),
  (
    2024,
    'I',
    400001,
    600000,
    'Next',
    '200,000',
    25,
    50000
  ),
  (
    2024,
    'J',
    600001,
    1000000,
    'Next',
    '400,000',
    26,
    104000
  ),
  (
    2024,
    'K',
    1000001,
    NULL,
    'Excess',
    'Every next RM',
    30,
    NULL
  );

INSERT INTO
  corporate_tax_rates (
    year,
    category,
    chargeable_income_min,
    chargeable_income_max,
    rate,
    notes
  )
VALUES
  (
    2024,
    'SME',
    0,
    500000,
    17.00,
    'For SMEs with paid-up capital of RM2.5 million or less, and gross business income of RM50 million or less.'
  ),
  (
    2024,
    'SME (Excess)',
    500001,
    NULL,
    24.00,
    'For SMEs, on income exceeding RM500,000.'
  ),
  (
    2024,
    'Non-SME',
    NULL,
    NULL,
    24.00,
    'For companies with paid-up capital of more than RM2.5 million.'
  );

INSERT INTO
  tax_reliefs (
    year,
    category,
    item,
    relief_amount,
    notes
  )
VALUES
  (
    2024,
    'Individual',
    'Individual and dependent relatives',
    9000,
    'Automatic'
  ),
  (
    2024,
    'Medical',
    'Medical treatment for parents',
    8000,
    'Limited'
  ),
  (
    2024,
    'Lifestyle',
    'Purchase of books, journals, magazines, etc.',
    2500,
    'Limited'
  ),
  (
    2024,
    'Education',
    'Self-education fees (up to tertiary)',
    7000,
    'Limited'
  ); 