name = "ibnzelt-official"
compatibility_date = "2025-06-21"
main = "workers-site/index.js"

[site]
bucket = "./dist"

[env.production]
name = "ibnzelt-official"
routes = [
  "ibnzelt.com/*",
  "www.ibnzelt.com/*"
]

[env.development]
name = "ibnzelt-official-dev" 