// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL) throw new Error("VITE_SUPABASE_URL is required");
if (!SUPABASE_PUBLISHABLE_KEY) throw new Error("VITE_SUPABASE_ANON_KEY is required");

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

declare global {
  interface ImportMeta {
    readonly env: {
      VITE_SUPABASE_URL: string;
      VITE_SUPABASE_ANON_KEY: string;
      [key: string]: string;
    };
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);