// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Add __supabase to the Window type for TypeScript
declare global {
  interface Window {
    __supabase?: ReturnType<typeof createClient<Database>>;
  }
}

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) throw new Error('Missing Supabase env vars');

let _supabase: ReturnType<typeof createClient<Database>>;

if (typeof window !== 'undefined') {
  if (!window.__supabase) {
    window.__supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
  }
  _supabase = window.__supabase;
} else {
  if (!_supabase) {
    _supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
  }
}

export const supabase = _supabase;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client"; 