// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://zltfmtsqxetzsjusqwep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsdGZtdHNxeGV0enNqdXNxd2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzY4MzgsImV4cCI6MjA2NjAxMjgzOH0.b53XzUgUIjQr2EivOeefgUQTVNJTxVWH7jqUD6aykKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);