// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL) throw new Error("VITE_SUPABASE_URL is required");
if (!SUPABASE_PUBLISHABLE_KEY) throw new Error("VITE_SUPABASE_ANON_KEY is required");

// Singleton pattern for Supabase client (prevents multiple GoTrueClient instances)
let _supabase: ReturnType<typeof createClient<Database>>;

// @ts-ignore
if (typeof window !== 'undefined') {
  // @ts-ignore
  if (!window.__supabase) {
    // @ts-ignore
    window.__supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
  }
  // @ts-ignore
  _supabase = window.__supabase;
} else {
  // SSR or Node.js
  if (!_supabase) {
    _supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
  }
}

export const supabase = _supabase;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client"; 